#!/bin/bash
# Copyright 2002-2003 by Kai 'Oswald' Seidler, oswald@apachefriends.org, GPL-licensed

. /opt/lampp/share/lampp/lampplib

de="false"
case $LANG in
        de*) de="true";;
esac

if test "$1" = "check"
then    
        check="true"
else    
        check="false"
fi

bon="[1m"
boff="[m"


f="/opt/lampp/etc/my.cnf"

p=`awk '
BEGIN {sn=1}
/^\[mysqld\]/,/^\[mysqldump\]/ { 
		if($1=="skip-networking")
		{
			sn=0
		}
	}
END {
	print sn
	}
' $f`

if test "$p" -gt 0
then
        $check && exit 1

	$de && echo "XAMPP: ${bon}MySQL ist ueber's Netzwerk erreichbar.${boff}"
	$de || echo "XAMPP: ${bon}MySQL is accessable via network.${boff}"
        $de && q="Normalerweise wird dies nicht benoetigt. Soll ich es abschalten?"
        $de || q="Normaly that's not recommended. Do you want me to turn it off?"
        if asky "$q"
	then
		$awk '
		/^\[mysqld\]/,/^\[mysqldump\]/ { 
                                if($1=="#skip-networking")
                                {
                                        print "# commented in by lampp security"
                                        print $0
                                        print "skip-networking"
                                        next
                                }
			}
			{
				print
			}
		' $f > /tmp/lampp$$
		cp /tmp/lampp$$ $f
		rm /tmp/lampp$$ 
		$de && echo "XAMPP: Abgeschaltet!"
		$de || echo "XAMPP: Turned off."
		if test -f /opt/lampp/var/mysql/`/bin/hostname`.pid
		then
			/opt/lampp/lampp stopmysql
			sleep 2
			/opt/lampp/lampp startmysql
			sleep 5
		fi
	fi
else
        $check && exit 0

	$de && echo "XAMPP: MySQL ist nicht ueber's Netzwerk erreichbar. Gut!"
	$de || echo "XAMPP: MySQL is not accessable via network. Good."
fi

