#!/bin/bash
# Copyright 2002-2003 by Kai 'Oswald' Seidler, oswald@apachefriends.org, GPL-licensed

. /opt/lampp/share/lampp/lampplib

if test "$1" = "check"
then    
        check="true"
else    
        check="false"
fi

lc="/opt/lampp/etc/lampp"
f="/opt/lampp/etc/proftpd.conf"

bon="[1m"
boff="[m"

if egrep "^UserPassword nobody wRPBu8u4YP0CY" $f > /dev/null 2>&1
then
        $check && exit 1

	$de && echo "XAMPP: ${bon}Das FTP-Passwort fuer 'nobody' ist noch auf 'lampp' gestellt.${boff}"
	$de || echo "XAMPP: ${bon}The FTP password for user 'nobody' is still set to 'lampp'.${boff}"
	if test ! -f $lc/startftp
	then
		$de && echo "XAMPP: (Da aber ProFTPD nicht gestartet wird, ist das auch nicht so schlimm.)"
		$de || echo "XAMPP: (But you didn't use ProFTPD so this is not critical.)"
	fi
	$de && q="Moechtest Du das Passwort aendern?"
	$de || q="Do you want to change the password?"
	ask="asky";
else
        $check && exit 0

	$de && echo "XAMPP: ProFTPD hat ein neues FTP-Passwort. Super!"
	$de || echo "XAMPP: ProFTPD has a new FTP password. Great!"
	$de && q="Moechtest Du trotzdem das Passwort aendern?"
	$de || q="Do you want to change the password anyway?"
	ask="askn";
fi

if $ask "$q"
then
	$de && q="Passwort:"
	$de || q="Password:"
	$de && q2="Passwort (Wiederholung):"
	$de || q2="Password (again):"
	word=`askp "$q" "$q2"`
	$awk -vpw="$word" '
/^UserPassword nobody wRPBu8u4YP0CY/ {
		print "# commented out by lampp security"
		print "#"$0
		print "UserPassword nobody "pw
		next
	}
	{
		print
	}
' $f > /tmp/lampp$$
	cp /tmp/lampp$$ $f
	rm /tmp/lampp$$
	/opt/lampp/lampp reloadftp
fi
