#!/bin/bash
# Copyright 2003 by Kai 'Oswald' Seidler, oswald@apachefriends.org, GPL-licensed

. /opt/lampp/share/lampp/lampplib

f="/opt/lampp/etc/httpd.conf"
	$awk '
f==0 && $0 == "#ScoreBoardFile logs/apache_runtime_status" {
	print "# commented in(!!!) by lampp compatibility check"
	print $0
	print "ScoreBoardFile logs/apache_runtime_status"
	f=1
	next
}
{
	print
}
' $f > /tmp/lampp$$
cp /tmp/lampp$$ $f
rm /tmp/lampp$$ 
